apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-galaxy
  namespace: default
  labels:
    app: hello-galaxy
spec:
  replicas: 5
  minReadySeconds: 4
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hello-galaxy
    spec:
      containers:
      - name: hello-galaxy
        image: hello-galaxy:v1
        ports:
        - containerPort: 8080 