apiVersion: v1
kind: Service
metadata: 
  name: hello-galo-pod-svc
  labels:
    app: hello-galo-pod-svc
spec:
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  selector:
    app: hello-galo-pod
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer